import { IPlayer } from "../types/cores/player";

export const playersData = (): IPlayer[] => [
  {
    name: "player-0",
    number: 50,
    positionX: 0,
    positionY: 1,
    isReplaced: false,
  },
  {
    name: "player-1",
    number: 51,
    positionX: 1,
    positionY: 1,
    isReplaced: false,
  },
  {
    name: "player-2",
    number: 52,
    positionX: 1,
    positionY: 2,
    isReplaced: false,
  },
  {
    name: "player-3",
    number: 53,
    positionX: 1,
    positionY: 3,
    isReplaced: false,
  },
  {
    name: "player-4",
    number: 54,
    positionX: 1,
    positionY: 4,
    isReplaced: false,
  },
  {
    name: "player-5",
    number: 55,
    positionX: 2,
    positionY: 1,
    isReplaced: false,
  },
  {
    name: "player-6",
    number: 56,
    positionX: 2,
    positionY: 2,
    isReplaced: false,
  },
  {
    name: "player-7",
    number: 57,
    positionX: 3,
    positionY: 1,
    isReplaced: false,
  },
  {
    name: "player-8",
    number: 58,
    positionX: 3,
    positionY: 2,
    isReplaced: false,
  },
  {
    name: "player-9",
    number: 59,
    positionX: 3,
    positionY: 3,
    isReplaced: false,
  },
  {
    name: "player-10",
    number: 60,
    positionX: 4,
    positionY: 1,
    isReplaced: false,
  },
];
export const playersReplaceData = (): IPlayer[] => [
  {
    name: "player-10",
    number: 70,
    positionX: 0,
    positionY: 1,
    isReplaced: false,
  },
  {
    name: "player-11",
    number: 71,
    positionX: 1,
    positionY: 1,
    isReplaced: false,
  },
  {
    name: "player-12",
    number: 72,
    positionX: 1,
    positionY: 2,
    isReplaced: false,
  },
  {
    name: "player-13",
    number: 73,
    positionX: 1,
    positionY: 3,
    isReplaced: false,
  },
  {
    name: "player-14",
    number: 74,
    positionX: 1,
    positionY: 4,
    isReplaced: true,
  },
  {
    name: "player-15",
    number: 75,
    positionX: 2,
    positionY: 1,
    isReplaced: false,
  },
  {
    name: "player-16",
    number: 76,
    positionX: 2,
    positionY: 2,
    isReplaced: true,
  },
  {
    name: "player-17",
    number: 77,
    positionX: 3,
    positionY: 1,
    isReplaced: true,
  },
  {
    name: "player-18",
    number: 78,
    positionX: 3,
    positionY: 2,
    isReplaced: false,
  },
  {
    name: "player-19",
    number: 79,
    positionX: 3,
    positionY: 3,
    isReplaced: false,
  },
  {
    name: "player-20",
    number: 80,
    positionX: 4,
    positionY: 1,
    isReplaced: false,
  },
];
