import { IPlayer } from "../types/cores/player";

export const playersData = (): IPlayer[] => [
  {
    firstName: "Alexander",
    lastName: "Plagborg",
    id: 50,
    gridX: 0,
    gridY: 1,
    substituted: false,
    ghost: false,
  },
  {
    firstName: "Andreas",
    lastName: "Louridsen",
    id: 51,
    gridX: 1,
    gridY: 1,
    substituted: false,
    ghost: false,
  },
  {
    firstName: "Christan",
    lastName: "Jorgensen",
    id: 52,
    gridX: 1,
    gridY: 2,
    substituted: false,
    ghost: false,
  },
  {
    firstName: "Gabriel",
    lastName: "Shawol",
    id: 53,
    gridX: 1,
    gridY: 3,
    substituted: false,
    ghost: false,
  },
  {
    firstName: "Jakob",
    lastName: "Agger",
    id: 54,
    gridX: 1,
    gridY: 4,
    substituted: false,
    ghost: false,
  },
  {
    firstName: "Alexander",
    lastName: "Jorgensen",
    id: 55,
    gridX: 2,
    gridY: 1,
    substituted: false,
    ghost: false,
  },
  {
    firstName: "Agger",
    lastName: "Christan",
    id: 56,
    gridX: 2,
    gridY: 2,
    substituted: false,
    ghost: false,
  },
  {
    firstName: "Jorgensen",
    lastName: "Jorgensen",
    id: 57,
    gridX: 3,
    gridY: 1,
    substituted: false,
    ghost: false,
  },
  {
    firstName: "Alexander",
    lastName: "Shawol",
    id: 58,
    gridX: 3,
    gridY: 2,
    substituted: false,
    ghost: false,
  },
  {
    firstName: "Christan",
    lastName: "Agger",
    id: 59,
    gridX: 3,
    gridY: 3,
    substituted: false,
    ghost: false,
  },
  {
    firstName: "Shawol",
    lastName: "Jorgensen",
    id: 60,
    gridX: 4,
    gridY: 1,
    substituted: false,
    ghost: false,
  },
];
export const playersReplaceData = (): IPlayer[] => [
  {
    firstName: "player-10",
    lastName: "",
    id: 70,
    gridX: 0,
    gridY: 1,
    substituted: false,
    ghost: false,
  },
  {
    firstName: "player-11",
    lastName: "",
    id: 71,
    gridX: 1,
    gridY: 1,
    substituted: false,
    ghost: false,
  },
  {
    firstName: "player-12",
    lastName: "",
    id: 72,
    gridX: 1,
    gridY: 2,
    substituted: false,
    ghost: false,
  },
  {
    firstName: "player-13",
    lastName: "",
    id: 73,
    gridX: 1,
    gridY: 3,
    substituted: false,
    ghost: false,
  },
  {
    firstName: "player-14",
    lastName: "",
    id: 74,
    gridX: 1,
    gridY: 4,
    substituted: true,
    ghost: false,
  },
  {
    firstName: "player-15",
    lastName: "",
    id: 75,
    gridX: 2,
    gridY: 1,
    substituted: false,
    ghost: false,
  },
  {
    firstName: "player-16",
    lastName: "",
    id: 76,
    gridX: 2,
    gridY: 2,
    substituted: true,
    ghost: false,
  },
  {
    firstName: "player-17",
    lastName: "",
    id: 77,
    gridX: 3,
    gridY: 1,
    substituted: true,
    ghost: false,
  },
  {
    firstName: "player-18",
    lastName: "",
    id: 78,
    gridX: 3,
    gridY: 2,
    substituted: false,
    ghost: false,
  },
  {
    firstName: "player-19",
    lastName: "",
    id: 79,
    gridX: 3,
    gridY: 3,
    substituted: false,
    ghost: false,
  },
  {
    firstName: "player-20",
    lastName: "",
    id: 80,
    gridX: 4,
    gridY: 1,
    substituted: false,
    ghost: false,
  },
];
